# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-25 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='shot_boundary',
        ),
        migrations.RemoveField(
            model_name='shot',
            name='in_commercial',
        ),
    ]
