# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-26 22:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_auto_20190225_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='face',
            name='background',
        ),
        migrations.RemoveField(
            model_name='face',
            name='blurriness',
        ),
        migrations.RemoveField(
            model_name='face',
            name='is_host',
        ),
    ]
