# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-26 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_auto_20190226_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='srt_extension',
            field=models.CharField(default='', max_length=256),
        ),
    ]
